# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='total_pokes',
            field=models.IntegerField(null=True),
        ),
    ]
