# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_users_total_pokes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='total_pokes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
